<?xml version="1.0"?>
<package format="2">
  <name>rtp_sender</name>
  <version>0.0.0</version>
  <description>The rtp_sender package</description>

  <maintainer email="contact@cjt-robotics.de">CJT-Robotics</maintainer>

  <license>TODO</license>

  <url type="website">https://cjt-robotics.de</url>
  <url type="repository">https://github.com/CJT-Robotics/rtp_receiver.git</url>

  <author email="markus.peltsarszky@gmail.com">Markus Peltsarszky</author>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>nodelet</build_depend>
  <build_depend>rospy</build_depend>
  <build_export_depend>nodelet</build_export_depend>
  <build_export_depend>rospy</build_export_depend>
  <exec_depend>nodelet</exec_depend>
  <exec_depend>rospy</exec_depend>


  <export>
  </export>
</package>
